import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(root, '..');

const codeSources = [
  'src/code/00-bootstrap.js',
  'src/code/10-command-center.js',
  'src/code/15-fix-engine.js',
  'src/code/20-menu-generator.js',
  'src/code/30-style-guide.js',
  'src/code/40-table-builder.js',
];

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), 'utf8').replace(/\r\n/g, '\n');
}

function write(relPath, value) {
  fs.writeFileSync(path.join(root, relPath), value.replace(/\r\n/g, '\n'));
}

function buildCode() {
  const header = '// Generated by klic-figma-toolkit/build-toolkit.mjs. Do not edit directly.\n';
  return `${header}${codeSources.map(read).map((part) => part.trim()).join('\n\n')}\n`;
}

function buildUi() {
  const template = read('src/ui/index.html');
  const styles = read('src/ui/styles.css').trim();
  const i18n = read('src/ui/i18n.js').trim();
  const app = read('src/ui/app.js').trim();
  return template
    .replace('<!-- @klic-generated -->', '<!-- Generated by klic-figma-toolkit/build-toolkit.mjs. Do not edit directly. -->')
    .replace('<!-- @klic-styles -->', `<style>\n${styles}\n</style>`)
    .replace('<!-- @klic-script -->', `<script>\n${i18n}\n\n${app}\n</script>`)
    .replace(/\r\n/g, '\n');
}

function checkGenerated(relPath, expected) {
  const actualPath = path.join(root, relPath);
  const actual = fs.existsSync(actualPath) ? fs.readFileSync(actualPath, 'utf8').replace(/\r\n/g, '\n') : '';
  if (actual !== expected) {
    throw new Error(`${relPath} is out of date. Run: node klic-figma-toolkit/build-toolkit.mjs`);
  }
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const code = buildCode();
  const ui = buildUi();
  if (checkOnly) {
    checkGenerated('code.js', code);
    checkGenerated('ui.html', ui);
    console.log('KLIC generated plugin files are up to date.');
    return;
  }
  write('code.js', code);
  write('ui.html', ui);
  console.log('KLIC generated plugin files rebuilt.');
}

main();
